server:
  port: 8080
blog:
  swagger:
    enabled: true #是否启用swagger
    docket:
      user:
        title: 用户模块
        base-package: com.nbchen.demo.knife4j.controller.user
      menu:
        title: 菜单模块
        base-package: com.nbchen.demo.knife4j.controller.menu
    # 不分组,与docket互斥
#    title: test模块
#    base-package: com.nbchen.demo.knife4j.controller